export const DOG_BREEDS = [
  'Affenpinscher', 'Afghan Hound', 'Airedale Terrier', 'Akita', 'Alaskan Malamute',
  'American Bulldog', 'American Cocker Spaniel', 'American Eskimo Dog', 'American Foxhound',
  'American Pit Bull Terrier', 'American Staffordshire Terrier', 'American Water Spaniel',
  'Anatolian Shepherd Dog', 'Australian Cattle Dog', 'Australian Kelpie', 'Australian Shepherd',
  'Australian Terrier', 'Basenji', 'Basset Hound', 'Beagle', 'Bearded Collie',
  'Beauceron', 'Bedlington Terrier', 'Belgian Malinois', 'Belgian Sheepdog',
  'Belgian Tervuren', 'Bernese Mountain Dog', 'Bichon Frise', 'Black and Tan Coonhound',
  'Black Russian Terrier', 'Bloodhound', 'Bluetick Coonhound', 'Boerboel',
  'Border Collie', 'Border Terrier', 'Borzoi', 'Boston Terrier',
  'Bouvier des Flandres', 'Boxer', 'Boykin Spaniel', 'Briard',
  'Brittany', 'Brussels Griffon', 'Bull Terrier', 'Bulldog (English)',
  'Bullmastiff', 'Cairn Terrier', 'Canaan Dog', 'Cane Corso',
  'Cardigan Welsh Corgi', 'Cavalier King Charles Spaniel', 'Chesapeake Bay Retriever',
  'Chihuahua', 'Chinese Crested', 'Chinese Shar-Pei', 'Chinook',
  'Chow Chow', 'Clumber Spaniel', 'Cockapoo', 'Cocker Spaniel',
  'Collie', 'Corgi (Pembroke Welsh)', 'Coton de Tulear', 'Dachshund',
  'Dalmatian', 'Dandie Dinmont Terrier', 'Doberman Pinscher', 'Dogo Argentino',
  'Dogue de Bordeaux', 'Dutch Shepherd', 'English Cocker Spaniel', 'English Foxhound',
  'English Setter', 'English Springer Spaniel', 'English Toy Spaniel', 'Entlebucher Mountain Dog',
  'Field Spaniel', 'Finnish Lapphund', 'Finnish Spitz', 'Flat-Coated Retriever',
  'French Bulldog', 'German Pinscher', 'German Shepherd', 'German Shorthaired Pointer',
  'German Wirehaired Pointer', 'Giant Schnauzer', 'Glen of Imaal Terrier',
  'Goldador', 'Golden Retriever', 'Goldendoodle', 'Gordon Setter',
  'Great Dane', 'Great Pyrenees', 'Greater Swiss Mountain Dog', 'Greyhound',
  'Harrier', 'Havanese', 'Hovawart', 'Ibizan Hound',
  'Icelandic Sheepdog', 'Irish Red and White Setter', 'Irish Setter', 'Irish Terrier',
  'Irish Water Spaniel', 'Irish Wolfhound', 'Italian Greyhound', 'Jack Russell Terrier',
  'Japanese Chin', 'Japanese Spitz', 'Jindo', 'Kai Ken',
  'Karelian Bear Dog', 'Keeshond', 'Kerry Blue Terrier', 'King Charles Spaniel',
  'Kishu Ken', 'Komondor', 'Kooikerhondje', 'Korean Jindo',
  'Kuvasz', 'Labradoodle', 'Labrador Retriever', 'Lagotto Romagnolo',
  'Lakeland Terrier', 'Lancashire Heeler', 'Leonberger', 'Lhasa Apso',
  'Löwchen', 'Maltese', 'Maltipoo', 'Manchester Terrier',
  'Maremma Sheepdog', 'Mastiff', 'Miniature American Shepherd', 'Miniature Bull Terrier',
  'Miniature Pinscher', 'Miniature Poodle', 'Miniature Schnauzer', 'Mixed Breed',
  'Morkie', 'Mudi', 'Neapolitan Mastiff', 'Newfoundland',
  'Norfolk Terrier', 'Norwegian Buhund', 'Norwegian Elkhound', 'Norwegian Lundehund',
  'Norwich Terrier', 'Nova Scotia Duck Tolling Retriever', 'Old English Sheepdog',
  'Otterhound', 'Papillon', 'Parson Russell Terrier', 'Patterdale Terrier',
  'Pekingese', 'Pembroke Welsh Corgi', 'Peruvian Inca Orchid', 'Petit Basset Griffon Vendéen',
  'Pharaoh Hound', 'Plott Hound', 'Pointer', 'Polish Lowland Sheepdog',
  'Pomeranian', 'Pomsky', 'Poodle (Standard)', 'Poodle (Miniature)', 'Poodle (Toy)',
  'Portugese Water Dog', 'Portuguese Podengo', 'Presa Canario', 'Pug',
  'Puggle', 'Puli', 'Pumi', 'Pyrenean Shepherd',
  'Rat Terrier', 'Redbone Coonhound', 'Rhodesian Ridgeback', 'Rottweiler',
  'Russell Terrier', 'Russian Toy', 'Saint Bernard', 'Saluki',
  'Samoyed', 'Schipperke', 'Schnauzer (Giant)', 'Schnauzer (Miniature)', 'Schnauzer (Standard)',
  'Schnoodle', 'Scottish Deerhound', 'Scottish Terrier', 'Sealyham Terrier',
  'Shetland Sheepdog', 'Shiba Inu', 'Shih Tzu', 'Shih-Poo',
  'Siberian Husky', 'Silky Terrier', 'Skye Terrier', 'Sloughi',
  'Smooth Fox Terrier', 'Soft Coated Wheaten Terrier', 'Spanish Mastiff', 'Spanish Water Dog',
  'Spinone Italiano', 'Staffordshire Bull Terrier', 'Standard Poodle', 'Standard Schnauzer',
  'Sussex Spaniel', 'Swedish Vallhund', 'Taiwan Dog', 'Thai Ridgeback',
  'Tibetan Mastiff', 'Tibetan Spaniel', 'Tibetan Terrier', 'Toy Fox Terrier',
  'Toy Poodle', 'Treeing Walker Coonhound', 'Vizsla', 'Weimaraner',
  'Welsh Springer Spaniel', 'Welsh Terrier', 'West Highland White Terrier',
  'Whippet', 'White Swiss Shepherd', 'Wire Fox Terrier', 'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla', 'Xoloitzcuintli', 'Yorkshire Terrier', 'Yorkipoo',
].sort()

export const CAT_BREEDS = [
  'Abyssinian', 'American Bobtail', 'American Curl', 'American Shorthair', 'American Wirehair',
  'Balinese', 'Bengal', 'Birman', 'Bombay', 'British Longhair', 'British Shorthair',
  'Burmese', 'Burmilla', 'Chartreux', 'Chausie', 'Cornish Rex',
  'Devon Rex', 'Domestic Longhair', 'Domestic Mediumhair', 'Domestic Shorthair',
  'Egyptian Mau', 'European Shorthair', 'Exotic Shorthair', 'Havana Brown',
  'Himalayan', 'Japanese Bobtail', 'Javanese', 'Khao Manee',
  'Korat', 'LaPerm', 'Lykoi', 'Maine Coon',
  'Manx', 'Mixed Breed', 'Munchkin', 'Nebelung', 'Norwegian Forest Cat',
  'Ocicat', 'Oriental Longhair', 'Oriental Shorthair', 'Persian',
  'Peterbald', 'Pixie-Bob', 'Ragamuffin', 'Ragdoll',
  'Russian Blue', 'Savannah', 'Scottish Fold', 'Selkirk Rex',
  'Siamese', 'Siberian', 'Singapura', 'Snowshoe',
  'Somali', 'Sphynx', 'Thai', 'Tonkinese',
  'Toyger', 'Turkish Angora', 'Turkish Van',
].sort()
