import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  const user = await getCurrentUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const rows = await prisma.$queryRawUnsafe<any[]>(
    `SELECT e.*, u.name as submitted_by_name FROM eod_closings e LEFT JOIN users u ON u.id = e.created_by WHERE e.id = $1::uuid LIMIT 1`,
    params.id
  )
  if (!rows.length) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  const e = rows[0]
  const breakdown = Array.isArray(e.payment_breakdown) ? e.payment_breakdown : JSON.parse(e.payment_breakdown || '[]')

  const methodRows = breakdown.map((m: any) => {
    const variance = parseFloat(m.variance || 0)
    const color = Math.abs(variance) > 5 ? '#dc2626' : Math.abs(variance) > 0 ? '#d97706' : '#16a34a'
    return `<tr>
      <td>${m.label || m.method}</td>
      <td class="num">S$${parseFloat(m.expected || 0).toFixed(2)}</td>
      <td class="num">S$${parseFloat(m.counted || 0).toFixed(2)}</td>
      <td class="num" style="color:${color}">S$${variance.toFixed(2)}</td>
    </tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>EOD Cash-Up — ${e.date}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a1a; padding: 32px; }
  h1 { font-size: 22px; color: #EC6496; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 13px; margin-bottom: 24px; }
  .meta { display: flex; gap: 32px; margin-bottom: 24px; background: #f9f9f9; padding: 12px 16px; border-radius: 6px; }
  .meta div { }
  .meta label { font-size: 11px; color: #888; display: block; }
  .meta strong { font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th { background: #EC6496; color: white; padding: 8px 12px; text-align: left; font-size: 12px; }
  td { padding: 7px 12px; border-bottom: 1px solid #eee; }
  .num { text-align: right; font-family: monospace; }
  tr.total td { font-weight: bold; background: #fff0f5; border-top: 2px solid #EC6496; }
  .section-title { font-size: 14px; font-weight: bold; color: #333; margin: 20px 0 8px; border-left: 4px solid #EC6496; padding-left: 8px; }
  .float-box { display: flex; gap: 20px; flex-wrap: wrap; margin-bottom: 20px; }
  .float-item { flex: 1; min-width: 140px; background: #f9f9f9; padding: 10px 14px; border-radius: 6px; }
  .float-item label { font-size: 11px; color: #888; display: block; margin-bottom: 2px; }
  .float-item strong { font-size: 18px; }
  .banking strong { font-size: 18px; color: #EC6496; }
  .footer { margin-top: 32px; font-size: 11px; color: #aaa; border-top: 1px solid #eee; padding-top: 12px; }
  @media print { body { padding: 16px; } }
</style>
</head>
<body>
  <h1>🐾 RehabVet — End of Day Cash-Up</h1>
  <div class="subtitle">513 Serangoon Road #01-01 · hello@rehabvet.com · 6291 6881</div>

  <div class="meta">
    <div><label>Date</label><strong>${e.date}</strong></div>
    <div><label>Submitted by</label><strong>${e.submitted_by_name || '—'}</strong></div>
    <div><label>Submitted at</label><strong>${e.submitted_at ? new Date(e.submitted_at).toLocaleString('en-SG') : '—'}</strong></div>
    <div><label>Total Invoices</label><strong>${e.invoice_count}</strong></div>
  </div>

  <div class="section-title">Payment Breakdown</div>
  <table>
    <thead><tr><th>Method</th><th class="num">Expected (System)</th><th class="num">Counted</th><th class="num">Variance</th></tr></thead>
    <tbody>
      ${methodRows}
      <tr class="total">
        <td>TOTAL</td>
        <td class="num">S$${parseFloat(e.total_expected || 0).toFixed(2)}</td>
        <td class="num">S$${parseFloat(e.total_counted || 0).toFixed(2)}</td>
        <td class="num">S$${parseFloat(e.total_variance || 0).toFixed(2)}</td>
      </tr>
    </tbody>
  </table>

  <div class="section-title">Cash Float & Banking</div>
  <div class="float-box">
    <div class="float-item"><label>Float In (from yesterday)</label><strong>S$${parseFloat(e.float_in || 0).toFixed(2)}</strong></div>
    <div class="float-item"><label>Cash Counted</label><strong>S$${parseFloat(breakdown.find((m:any)=>m.method==='cash')?.counted || 0).toFixed(2)}</strong></div>
    <div class="float-item"><label>Float Left in Till</label><strong>S$${parseFloat(e.float_out || 0).toFixed(2)}</strong></div>
    <div class="float-item banking"><label>Banking Today</label><strong>S$${parseFloat(e.banking || 0).toFixed(2)}</strong></div>
  </div>

  ${e.notes ? `<div class="section-title">Notes</div><p style="margin-bottom:16px">${e.notes}</p>` : ''}

  <div class="footer">
    Generated by RehabVet App · ${new Date().toLocaleString('en-SG')} · This is an official end-of-day record.
  </div>

  <script>window.onload = () => window.print()</script>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    },
  })
}
